# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: docker image
          command: |
            docker info
            docker build -t coinpit/nodejs:v8.11.1 .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push coinpit/nodejs
